// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.GameView = (function(_super) {
    __extends(GameView, _super);

    function GameView() {
      return GameView.__super__.constructor.apply(this, arguments);
    }

    GameView.prototype.template = _.template('<button class="hit-button">Hit</button> <button class="stand-button">Stand</button> <div class="player-hand-container"></div> <div class="dealer-hand-container"></div>');

    GameView.prototype.events = {
      "click .hit-button": function() {
        return this.model.get('playerHand').hit();
      },
      "click .stand-button": function() {
        return this.model.get('playerHand').stand();
      }
    };

    GameView.prototype.initialize = function() {
      console.log(this);
      this.model.get('playerHand').on('bust', (function(_this) {
        return function() {
          _this.showBusted();
          return _this.model.checkScores();
        };
      })(this));
      this.model.get('playerHand').on('bust', (function(_this) {
        return function() {
          return _this.disButton();
        };
      })(this));
      this.model.get('playerHand').on('playerStand', (function(_this) {
        return function() {
          return _this.disButton();
        };
      })(this));
      this.model.on('dealerHasBust', (function(_this) {
        return function() {
          return _this.showDealerBusted();
        };
      })(this));
      this.model.on('playerHasWon', (function(_this) {
        return function() {
          return _this.showPlayerWon();
        };
      })(this));
      this.model.on('push', (function(_this) {
        return function() {
          return _this.showPush();
        };
      })(this));
      this.model.on('dealerHasWon', (function(_this) {
        return function() {
          return _this.showDealerWon();
        };
      })(this));
      return this.render();
    };

    GameView.prototype.showBusted = function() {
      return this.$el.find('.player-hand-container').prepend($('<h2>PLAYER BUSTED</h2>'));
    };

    GameView.prototype.showDealerBusted = function() {
      return this.$el.find('.player-hand-container').prepend($('<h2>DEALER BUSTED</h2>'));
    };

    GameView.prototype.showPlayerWon = function() {
      return this.$el.find('.player-hand-container').prepend($('<h2>PLAYER WON</h2>'));
    };

    GameView.prototype.showPush = function() {
      return this.$el.find('.player-hand-container').prepend($('<h2>PUSH</h2>'));
    };

    GameView.prototype.showDealerWon = function() {
      return this.$el.find('.player-hand-container').prepend($('<h2>DEALER WON</h2>'));
    };

    GameView.prototype.disButton = function() {
      return this.$el.find('button').attr('disabled', 'disabled');
    };

    GameView.prototype.render = function() {
      this.$el.children().detach();
      this.$el.html(this.template());
      this.$('.player-hand-container').html(new HandView({
        collection: this.model.get('playerHand')
      }).el);
      return this.$('.dealer-hand-container').html(new HandView({
        collection: this.model.get('dealerHand')
      }).el);
    };

    return GameView;

  })(Backbone.View);

}).call(this);

//# sourceMappingURL=GameView.map
